#!/bin/bash
# meisai-checker Mac アプリ インストーラー
# 使い方: bash install_mac_app.sh
set -e

echo "=== meisai-checker Mac アプリ インストーラー ==="

# uvx の確認
if ! command -v uvx &> /dev/null; then
    echo ""
    echo "[エラー] uv が見つかりません。"
    echo "以下のコマンドでインストールしてください:"
    echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
    exit 1
fi

APP_DIR="$HOME/Applications"
APP_PATH="$APP_DIR/meisai-checker.app"
ICONSET="$(mktemp -d)/meisai_checker.iconset"

mkdir -p "$APP_DIR"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"
mkdir -p "$ICONSET"

# --- アイコン生成 ---
ICON_PNG="$(mktemp).png"
echo "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAQRUlEQVR4nO3dPXIc1xmFYcjF3IkSJbMIKuAOnHAbZMLYKSOmjplAi3DCRSgQ9+BOlCjxCuhCySiRQ/zMT3ff77vneTJJVeSgZ0rnndsD4OYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5vTD6AeQ5vDyzZfRjwGgquXzL3ZpJy70Bow8wPrEwboEwAoMPsD+BMF1BMAFDD5APYLgPALgREYfoA8x8DwB8ASjD9CfGHiYAHiA4QeYjxD4lgD4iuEHmJ8Q+JMAMPwAkZbwnzkQ/cV7xw/AEhoCkV+04QcgPQSivljDD8BzlpAQ+NtNCOMPgL34y/SVY/gBuNQy8WnA1CcAxh8AO/KwKcvG8AOwtmWy04DpTgCMPwD2JSwAjD8AduY0UxxnGH4A9rY0vyXQ/gTA+ANgf8ICwPgDMNLh5ZsvXZ+BtgHQ+aIDMI9D0z1qGQBdLzYAczo03KV2AdDxIgMwv0OzfWoVAN0uLgBZDo12qk0AdLqoAOQ6NNmrFgHQ5WICQJfdKh8AHS4iAHTbr9IBUP3iAUDXHSsbAJUvGgB037OyAQAAhAVA1VoCgFl2rVwAVLxIADDbvpUKgGoXBwBm3blSAQAAhAVApSoCgNn3rkQAVLkYAJCyeyUCAAAIC4AKFQQAafv3t+QvHgBSd3D4CQAAEBQA3v0DwM2wPXQCAACBhgSAd/8AMHYXnQAAQKDdA8C7fwAYv49OAAAg0K4B4N0/ANTYSScAABBotwDw7h8A6uylEwAACLRLAHj3DwC1dtMJAAAEEgAAEGjzAHD8DwD19tMJAAAEEgAAEGjTAHD8DwA1d9QJAAAEEgAAEEgAAECgzQLA/X8AqLunTgAAIJAAAIBAAgAAAm0SAO7/A0DtXXUCAACBBAAABBIAABBIAABAoBejHwA1/Oe3299HPwbm8+nX/968e/fPn0Y/DuB7TgCATX38+C9xCQkB4FsAgWMiAOrtqxMAYBciAGoRAMBuRADUIQCAXYkAqEEAALsTATCeAACGEAEwlgAAhhEBMI4AAIYSATCGAACGEwGwPwEAlCACYF8CAChDBMB+BABQigiAfQgAoBwRANsTAEBJIgC2JQCAskQAbEcAAKWJANiGAADKEwGwPgEAtCACYF0CAGhDBMB6BADQigiAdQgAoB0RANcTAEBLIgCuIwCAtkQAXE4AAK2JALiMAADaEwFwPgEATEEEwHkEADANEQCnEwDAVEQAnEYAANMRAfA8AQBMSQTA0wQAMC0RAI8TAMDURAA8TAAA0xMB8D0BAEQQAfAtAQDEEAHwFwEARBEB8CcBAMQRASAAgFAigHROAIBYIoBkAgCIJgJIJQCAeCKARAIAwEkAgQQAwP85CSCJAAD4iggghQAAOCICSCAAAB4gApidAAB4hAhgZgIA4AkigFkJAIBniABmJAAATiACmI0AADiRCGAmAgDgDCKAWQgAgDOJAGYgAAAuIALoTgAAXEgE0JkAALiCCKArAQBwJRFARwIAYAUigG4EAMBKRACdvBj9AIB5vX7199EPAXiEEwAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAvlBQGzi7YdPi0vLSLfvXx88A/A4JwAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAE8suA2IRfxAJQmxMAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAI9GL0A2BObz98WkY/BljT7fvXB1eUmTgBAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJBfBsQm/OIUgNqcAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACBBAAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQKAXox8Ac3r74dMy+jHAmm7fvz64oszECQAABBIAABBIAABAIAEAAIEEAAAEEgAAEEgAAEAgAQAAgQQAAAQSAAAQSAAAQCABAACB/DIgNuEXpwDU5gQAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACCQAACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACvRj9AJjT2w+fltGPAdZ0+/71wRVlJk4AACCQAACAQAIAAAIJAAAIJAAAIJAAAIBAAgAAAgkAAAgkAAAgkAAAgEACAAACCQAACOSXAbEJvzgFoDYnAAAQSAAAQCABAACBBAAABBIAABBIAABAIN8GCDDAjx/X+7P+eLfen0UOAQDQZOjP/TuEAU8RAAAr+fnXtz/tMfineuixiALuCQCAKwa/28U7jgJBkEsAAEw++qcGgRjIIgAAwkb/MWIgiwAACB/+p2LAqcC8BADAkeThPyYE5iUAAIz+s9wemI8AAKJ5t38+pwJz8KOAgVjG/zqVfuYB53MCAMQx/OtxGtCXAABiGP7tCIF+3AIAIhj/fbgt0IcTAGBqhn9/TgN6EABs4u2HT4tLy2if//HvV6MfQ3oI+EFCdQkAYDqGvw6nAXX5DAAwFeNfk88G1CMAgGkY/9pEQC1uAQDtGf4+3BKowwkA0Jrx78lpwHgCAGjL+PcmAsYSAEBLxn8OImAcAQC0Y/znIgLGEABAK8Z/TiJgfwIAaMP4z00E7EsAAC0Y/wwiYD8CACjP+GcRAfvwg4DYxO371weXljX4bX6Z/CKh7TkBAMoy/tmcBGxLAAAlGX/uiIDtCACgHOPP10TANgQAAAQSAEAp3v3zEKcA6xMAQBnGn6eIgHUJAKAE488pRMB6BAAABBIAwHDe/XMOpwDrEADAUMafS4iA6wkAAAgkAIBhvPvnGk4BriMAgCGMP2sQAZcTAAAQSAAAu/PunzU5BbiMAACAQAIA2JV3/2zBKcD5BACwG+PPlkTAeQQAAAQSAMAuvPtnD04BTicAADjJb69uXamJCAAATh5/ETAPAQBszvF/b8ejf/fPlUPAbYDTCAAALlI5AnieAAA25d3/3CNfNQKcAjxPAABw1bhXvyXAwwQAsBnv/vu6ZNCrRYBTgKcJAABW4zSgDwEAwOrv5KudBvA9AQBswvF/T2sN98+/vr2pwG2AxwkAAKYcf54mAAAgkAAAVuf4v5+Z3/27DfAwAQAQbubx53ECACCY8c8lAABC+Va9bAIAWJX7/3k6HP37HMD3BABAIEf/CACAMMafOwIAIIj7/twTAABMed+fpwkAYDU+AFhb+tG/DwJ+SwAABEgff74nAAAmZ/x5iAAAmJgP/fEYAQDAsxz9z0cAAEzK0T9PEQDAKnwHQC3G/2G+E+AvAgBgMu77cwoBAMCD3PefmwAAmIijf04lAAAmYfw5hwAAmIDx51wCAAACCQCA5rz75xICAKAx48+lBABAU8afawgAgIY/PKfb46UeAQDEux/TxFH1w35yCQAg2vHod4gAR/+sQQAAsR4b0soRYPxZiwAAIj03pBUjoOJjoi8BAMQ5dUhnHVz3/bkjAIAoXUfd0T9rEwBAjEtGtEIwGH+2IACACNeM6MgIMP5sRQAAq/jt1e3vVS/lGiNa4SSA6/3xzlW898PNyg4v33xZ+88Eevjx401ZHd9Jd3zM1XUPgOXzL6vtthMAIMJaI7jXSYDxZ2sCAIjRJQKMP3sQAECU6hHgswbsRQAAcapHwBrc9+c5AgBYTfcPWI2OAEf/20p8fT5FAACR1nyHXOnbDL3z51QCAIhVZSwr30pgXgIAiDbT5wGqBA09CAAg3sgIcPTPKAIAWFXXD1qNiADjv5+ur8stCQCAARFg/BlNAADsHAEVPi8AAgCg6QcDfeiPawgAYHUz3G/dKgIc/e9vhtfjFgQAwE4RYPypRAAA7MB9f6oRAMAmZjl2rXafvdrjqW6W1+EWBABAk9Gt8jiYgwAAaDC+o/9+5iMAgM3Mdvw6aoSN/2Vme/2tTQAAnMEYMwsBAGxqxndhe0aA4LjMjK+7tQkAgKLDbPzZkgAANjfru7EtB9r4X27W19vaBADAFQw1XQkAgGIRICrYgwAAduFY9jTG3+tsLwIAoMhwG3/2JACA3cx+CvDcgN/9dyO/ndlfX2sTAMCuZv+f9GMD//W/fygEhMF1Zn9dbUEAAKzs1HG///fGnxEEALC7hHdrp4678b9ewutpCwIAYCPGncoEADCEd214HY0lAIBhRABeP+MIAAAIJACAoZwC4HUzhgAAhhMBeL3sTwAAQKDVA2D5/MsPa/+ZwPycAuB1su++OgEAyhABeH3sRwAApYgAvC72IQAAIJAAAMpxCoDXw/YEAFCSCMDrYFsCAChLBGTz/DcMAN8KCKzFCGTyvG+/q04AgPKMQRbP9z4EANCCUcjged6PAADaMA5z8/xOEgA+BwBswUjMyfO6/546AQDaMRZz8XyOIQCAlozGHDyP4wgAoC3j0Zvnb+IA8DkAYGtGpCfP2/gdfbHVHwyw95j8+NE1r87w1+EWADAN41Kb5ycsANwGAPZkZGryvNTbT7cAgOm4JVCH4a/LLQBgWsbH9edxmx4vfO3w8s2Xvf4ugGM+ILgf4dXj9rkTACCCUXKdGXQCcMcpAFCB04D1Cax+H573IUAgjg8Jrn8t6WfXWwC+JRCoxHi5ftXsuZNOAIBoTgMuv2b0tutnAO75LABQmc8IfM/oz3dK7gQA4IhTge+vBfMZcgJwxykA0EXiiYDh39eIz8g5AQA4YwxnjgGjn2XYCcAdpwBAZzPEgNEfb9R3yDkBAFhpPDsEgcGnxAnAHacAwMxGRoGxr28Z9O6/RADcEQFAmjXDwND3tAwc/ztuAQAMYLQZrcRvAxxdQQCQtnslAqDKxQCAlL0rEwAAQGgAVKkiAJh950oFQLWLAwCz7lu5AKh4kQBgtl0rGQAAQGgAVKwlAJhlz8oGQOWLBgDdd6x0AFS/eADQdb/KB0CHiwgA3XarRQB0uZgAsDTZqzYB0OmiApBpabRTrQKg28UFIMfSbJ/aBUDHiwzA3JaGu9QyALpebADmszTdo7YB0PmiAzCHpfEOtQ6A7hcfgL6W5vvT+sEfO7x882X0YwBgbkvz4Z/mBGDGJwWAmpaJdmaqAJjtyQGgjmWyfZnqiznmlgAA11omG/5pTwASnjQA9rFMvCPTfmHHnAYAcKpl4uGPOAFIezIBuN4SshcRX+QxpwEApA7/vagv9pgQAGAJG/57kV/0MSEAkGcJHf570V/8MSEAML/04b/nIjxACADMx/B/SwA8QQgA9Gf4HyYATiQGAPow+s8TABcQAwD1GP3zCIAVCAKA/Rn86wiADQgCgPUZ/HUJgJ2JA4DHGXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4GZd/wPn+2uSHyJpMAAAAABJRU5ErkJggg==" | base64 -d > "$ICON_PNG"

for size in 16 32 64 128 256 512; do
    sips -z $size $size "$ICON_PNG" --out "$ICONSET/icon_${size}x${size}.png" > /dev/null
    sips -z $((size*2)) $((size*2)) "$ICON_PNG" --out "$ICONSET/icon_${size}x${size}@2x.png" > /dev/null
done
iconutil -c icns "$ICONSET" -o "$APP_PATH/Contents/Resources/meisai_checker.icns"
rm "$ICON_PNG"

# --- Info.plist ---
cat > "$APP_PATH/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>meisai-checker</string>
    <key>CFBundleIconFile</key>
    <string>meisai_checker.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.aki0ka.meisai-checker</string>
    <key>CFBundleName</key>
    <string>meisai-checker</string>
    <key>CFBundleDisplayName</key>
    <string>meisai-checker</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
PLIST

# --- 起動スクリプト ---
cat > "$APP_PATH/Contents/MacOS/meisai-checker" << 'LAUNCHER'
#!/bin/bash
export PATH="/usr/local/bin:/opt/homebrew/bin:$HOME/.local/bin:$PATH"

if ! command -v uvx &> /dev/null; then
    osascript -e 'display alert "meisai-checker" message "uvx が見つかりません。\n\nuv をインストールしてください:\ncurl -LsSf https://astral.sh/uv/install.sh | sh" as critical'
    exit 1
fi

exec uvx --from meisai-checker@latest meisai-checker-gui
LAUNCHER
chmod +x "$APP_PATH/Contents/MacOS/meisai-checker"

# Finder に登録
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP_PATH" 2>/dev/null || true

echo ""
echo "✓ $APP_PATH を作成しました"
echo ""
echo "【Dock への追加】"
echo "  Finder で「移動 → ホーム → Applications」を開き、"
echo "  meisai-checker.app を Dock にドラッグしてください。"
